### ISSUE TITLE
Any plan to publish this library to a central repository?

### ISSUE THREAD

**Issue by abalonperin** [cb372/cats-retry#1]
Hi,

I am interested in using your library in one of my project. However, it's not available in any central repository so it's a bit difficult to use in production. Is there any plan to publish it?

Thank you,
Alex

**Comment by cb372** [comment]
Thanks for your interest.

Version 0.1.0 for Scala 2.12 is on its way to Maven Central now.

```
libraryDependencies ++= Seq(
  "com.github.cb372" %% "cats-retry-core" % "0.1.0",
  "com.github.cb372" %% "cats-retry-cats-effect" % "0.1.0"
)
```

I can add cross-builds for other Scala versions and Scala.js if necessary.

Please let me know how you get on with the library.

**Comment by abalonperin** [comment]
Awesome! 
Thank you for the quick reply and action.
I use Scala 2.12 so all good for me but of course more people might want to use `cats-retry` with Scala 2.11. 🙂 

I played with the library today and I am having some trouble using it with the `Eff` Monad (https://github.com/atnos-org/eff). I think that it's because `Eff` doesn't have an instance of `MonadError` but I am not sure yet. I will try a bit more and see if I can figure it out.
