### ISSUE TITLE
Include syntax to apply retries explicitly

### ISSUE THREAD

**Issue by LukaJCB** [cb372/cats-retry#105]

**Comment by cb372** [comment]
Could you give an example or some more details? Not quite sure what you mean.

**Comment by LukaJCB** [comment]
I was thinking of doing something like `task.retrying(policy, onError)` passing them explicitly rather than implicitly :)

**Comment by cb372** [comment]
I agree this would be nice. Passing a retry policy implicitly feels a bit weird.

I'm tempted to say we should break the API and rewrite the syntax to be explicit, rather than offering 2 different kinds of syntax to do the same thing.
