### ISSUE TITLE
Attempt to improve type inference

### ISSUE THREAD

**Issue by LukaJCB** [cb372/cats-retry#125]
I think the various `retrying` functions could all use some work in terms of type inference. For example, something like this doesn't compile:

```scala
retryingOnAllErrors(retryPolicy[IO], (_, _) => IO.unit)(ioa)
```

**Comment by cb372** [comment]
Agreed.

We should probably start with a few longer examples of what we’d like idiomatic usage of the API to look like, then see if we can get them to compile.
