### ISSUE TITLE
Policy to limit retries by total count

### ISSUE THREAD

**Issue by mihaisoloi** [cb372/cats-retry#19]
Is it possible to have a function with this signature?

```scala
def limitRetriesByTotalCount[M[_]: Applicative](
      maxRetries: Int,
      policy: RetryPolicy[M]
  ): RetryPolicy[M]
```

**Comment by cb372** [comment]
We could add that to the API, but it's already possible to limit the number of retries by composing the `limitRetries` policy with your base policy.

In fact, we do exactly this in the example in the "Composing policies" section of the documentation: https://cb372.github.io/cats-retry/docs/policies.html#composing-policies
