### ISSUE TITLE
v3.0 release

### ISSUE THREAD

**Issue by cb372** [cb372/cats-retry#287]
This issue is to track work towards a v3.0 release of cats-retry.

I'd like to see:

* upgrade to cats-effect 3 (and will there be a cats-core 3?)
* cross-build for Scala 3 (and drop 2.12?)
* #283 (make all predicates effectful)

Nice to have:

* port the tests from scalatest to MUnit - I get the impression this would make life easier when cross-building for Scala 3, but I don't have any hard facts to back that up

Any other breaking changes people want to suggest, now's your chance. Bring out your dead!

**Comment by landerlo** [comment]
Opened a WIP PR https://github.com/cb372/cats-retry/pull/291
Tackles the updates and fixes to Scala 3.0 and CE-3.0. Nothing about #283 or the mdoc examples for the moment.

**Comment by aeons** [comment]
A release supporting Scala 3 and CE2 would also be very useful.

**Comment by cb372** [comment]
Just remembered we have some deprecated methods in the API (e.g. `retryingM`). Let's delete those before v3.0.

**Comment by cb372** [comment]
v3.0.0 was released! It includes the upgrade to CE3 but not cross-building for Scala 3. We didn't delete those deprecated methods, but never mind.

I'll close this issue.

We still need to cross-build for Scala 3. We have a couple of PRs we can use as a reference for that:
* #294 - switching tests to munit and cross-building for Scala 3, on the series/2.x branch
* #291 - switching to munit, cross-building for Scala 3, and upgrading to CE3 (that part was superseded by #305)
