### ISSUE TITLE
Add combinator for sequential composition

### ISSUE THREAD

**Issue by LukaJCB** [cb372/cats-retry#39]
What I mean by this is to run the first `RetryPolicy` until it gives up and then go with the second. This should be associative and could also form a monoid with `RetryPolicy(const(GiveUp))`.

**Comment by cb372** [comment]
That sounds very reasonable.

I wonder how we should encode the monoid, as we already have a `BoundedSemilattice` instance in the companion object. Make it opt-in via an import I suppose. Is there a standard convention to follow when a library wants to provide multiple instances for the same type?

**Comment by LukaJCB** [comment]
Newtypes is the goto answer, at least in Haskell land, but the ergonomics in Scala haven't been that great yet, hopefully this will change soon, but for now we could `AnyVal` it, or just not provide an instance at all and just add as a method to the class, similar to what I suggested for the lattice issue :)

**Comment by cb372** [comment]
Fixed by #42
