### ISSUE TITLE
Migrate to mdoc

### ISSUE THREAD

**Issue by LukaJCB** [cb372/cats-retry#56]

**Comment by cb372** [comment]
+1. I actually looked into this a few days ago. It’s really easy to switch sbt-microsites to mdoc.

**Comment by Koisell** [comment]
That would be the reason for such choice ? (innocent question)

**Comment by Koisell** [comment]
As we meet this morning with @LukaJCB I will answer what I understood:
The main reason of the migration is performance, mdoc is quicker and so tut may simply stop being maintained since there is no reason to have two times the same tool.
So we migrate to mdoc.

**Comment by cb372** [comment]
This was done in #57
