### ISSUE TITLE
Update cats-effect to 1.0.0

### ISSUE THREAD

**Issue by fthomas** [cb372/cats-retry#6]
I was about to update cats-effect, fs2, doobie, and http4s to their latest versions in one of our projects and noticed that cats-retry is still on cats-effect 0.10.1. So cats-retry updated to cats-effect 1.0.0 would be much appreciated. :-)

Btw, I love cats-retry! It mitigates constraint violations exceptions in our CRUD app on parallel updates.

**Comment by fthomas** [comment]
Wow, that was fast. Many thanks, @cb372!

**Comment by cb372** [comment]
Thanks for the reminder! v0.2.0 is on its way to Maven Central.

Very happy to hear that somebody finds the library useful.
