### ISSUE TITLE
Can we replace Sleep by cats.effect.Timer?

### ISSUE THREAD

**Issue by julien-truffaut** [cb372/cats-retry#65]
```scala
trait Sleep[M[_]] {
  def sleep(delay: FiniteDuration): M[Unit]
}

trait Timer[F[_]] {
  def clock: Clock[F]
  def sleep(duration: FiniteDuration): F[Unit]
}
```

**Comment by cb372** [comment]
Potentially, yes. The reason for making my own Sleep type class was to avoid a cats-effect dependency in core. Currently core depends only on cats-core, and the cats-effect module provides a `Sleep` instance that trivially delegates to `Timer`.

**Comment by julien-truffaut** [comment]
ah makes sense, thanks Chris
