### ISSUE TITLE
Unhandled exception when deciding next retry on capped exponential backoff

### ISSUE THREAD

**Issue by xicmiah** [cb372/cats-retry#96]
Consider a policy: exponential backoff with capped delay and unlimited retries.
When repeatedly evaluating next decision for such policy, `RetryPolicies.decideNextRetry` starts throwing an exception.
Looks like it happens because uncapped delay eventually starts exceeding maximum possible `FiniteDuration`, and it's reachable in practice because of capped delay and uncapped retries.

Reproducing sample:
```scala
import retry._
import scala.concurrent.duration._

val basePolicy = RetryPolicies.exponentialBackoff(1.second)
val policy = RetryPolicies.capDelay(5.minutes, basePolicy)

Iterator.iterate(RetryStatus.NoRetriesYet)( status =>
  policy.decideNextRetry(status) match {
    case PolicyDecision.DelayAndRetry(delay) => status.addRetry(delay)
    case _ => ???
  }
).drop(35).next() // 34 returns RetryStatus(34,8011 seconds,Some(5 minutes))
```

```
java.lang.IllegalArgumentException: requirement failed: Duration is limited to +-(2^63-1)ns (ca. 292 years)
     at scala.concurrent.duration.FiniteDuration.<init>(Duration.scala:589)
     at scala.concurrent.duration.FiniteDuration.$times(Duration.scala:675)
     at retry.RetryPolicies$.$anonfun$fullJitter$1(RetryPolicies.scala:69)
     at retry.RetryPolicy$.$anonfun$lift$1(RetryPolicy.scala:88)
     at retry.RetryPolicy.$anonfun$meet$1(RetryPolicy.scala:45)
```

**Comment by cb372** [comment]
Sorry for the slow reply.

Good catch! I agree this is a problem.I'm surprised scalacheck has never caught it. Step one is to write a property-based test to reproduce the issue.

I can't think of an elegant solution right now, but maybe we should just add some logic to exponential backoff to make sure we never try to create a `FiniteDuration` larger than 2^63 - 1 ns.

We will need to make the same change to every retry policy that uses multiplication, so a single helper function would be a good idea.
